[project]
name = "code-of-q"
version = "0.1.0"
description = "QRコードスキャナーとジェネレーター"
authors = [
    {name = "toma"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "opencv-python>=4.8.0",
    "pillow>=10.0.0",
    "qrcode>=7.4.2",
    "PyQt6>=6.4.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
qr = "code_of_Q:main"

[tool.poetry]
packages = [
    { include = "code_of_Q.py" }
]
include = [
    { path = "Info.plist" }
]

[tool]
package-mode = false
